# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AirspaceGeometryBuilder
                                 A QGIS plugin
 Create polygon based on common used description in aviation.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-09
        copyright            : (C) 2021 by Paweł Strzelewicz
        email                : @
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AirspaceGeometryBuilder class from file AirspaceGeometryBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .airspace_geometry_builder import AirspaceGeometryBuilder
    return AirspaceGeometryBuilder(iface)
